Vendor libwebp 1.1.0 instead of using git submodule
Using the submodule made cargo failed the build if this repository was a git
cargo dependency with:

error: failed to load source for a dependency on `webp`

Caused by:
  Unable to update https://github.com/yanchith/webp?rev=3cad2f6e520a8b8d66c42d6b2ffe9c31ead18cf4

Caused by:
  failed to update submodule `libwebp`

Caused by:
  failed to fetch submodule `libwebp` from git@github.com:webmproject/libwebp.git

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

Caused by:
  error authenticating: failed connecting agent; class=Ssh (23)